import type { ComponentDefinition } from '@lowcode3d/shared'

export const lightComponentDefinition: ComponentDefinition = {
  type: 'light',
  title: '灯光',
  category: 'light',
  version: '1.0.0',
  capabilities: ['bindable', 'animatable', 'publishable'],
  defaultProps: {
    lightType: 'directional',
    color: '#ffffff',
    intensity: 1,
    distance: 10,
    angle: Math.PI / 6,
    penumbra: 0.1,
    castShadow: true,
  },
  properties: [
    {
      key: 'lightType',
      label: '灯光类型',
      type: 'select',
      group: '基础',
      defaultValue: 'directional',
      required: true,
      options: [
        { label: '环境光', value: 'ambient' },
        { label: '平行光', value: 'directional' },
        { label: '点光源', value: 'point' },
        { label: '聚光灯', value: 'spot' },
        { label: '半球光', value: 'hemisphere' },
      ],
    },
    {
      key: 'color',
      label: '颜色',
      type: 'color',
      group: '基础',
      defaultValue: '#ffffff',
      bindable: true,
    },
    {
      key: 'intensity',
      label: '强度',
      type: 'number',
      group: '基础',
      defaultValue: 1,
      min: 0,
      max: 20,
      step: 0.1,
      bindable: true,
    },
    { key: 'distance', label: '距离', type: 'number', group: '范围', defaultValue: 10, min: 0 },
    {
      key: 'angle',
      label: '角度',
      type: 'number',
      group: '范围',
      defaultValue: Math.PI / 6,
      min: 0,
    },
    {
      key: 'penumbra',
      label: '半影',
      type: 'number',
      group: '范围',
      defaultValue: 0.1,
      min: 0,
      max: 1,
      step: 0.01,
    },
    { key: 'castShadow', label: '投射阴影', type: 'boolean', group: '阴影', defaultValue: true },
  ],
}
