export const editorIcons = {
  scene: 'lucide:layers-3',
  model: 'mdi:cube-outline',
  material: 'lucide:palette',
  component: 'lucide:panels-top-left',
  annotation: 'lucide:map-pin',
  light: 'lucide:lightbulb',
  object: 'lucide:box',
  multiSelect: 'lucide:copy-check',
  transform: 'lucide:move-3d',
  render: 'lucide:aperture',
  data: 'carbon:data-base',
  event: 'lucide:radio-tower',
  environment: 'lucide:sun',
  postProcessing: 'lucide:sparkles',
  video: 'lucide:video',
  visible: 'lucide:eye',
  hidden: 'lucide:eye-off',
  locked: 'lucide:lock',
  unlocked: 'lucide:lock-open',
  focus: 'lucide:focus',
  more: 'lucide:ellipsis',
  delete: 'lucide:trash-2',
  copy: 'lucide:copy',
  reset: 'lucide:rotate-ccw',
  upload: 'lucide:upload',
  cover: 'lucide:camera',
  refresh: 'lucide:refresh-cw',
  star: 'lucide:star',
} as const

export type EditorIconName = keyof typeof editorIcons
